// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy-gHX38U33SshmMhcfGEoo_9dq0if7Jw',
    appId: '1:887229843621:web:c4a3174cc1910e151ae54c',
    messagingSenderId: '887229843621',
    projectId: 'assignment2-2b662',
    authDomain: 'assignment2-2b662.firebaseapp.com',
    storageBucket: 'assignment2-2b662.firebasestorage.app',
    measurementId: 'G-SVLBXVRX68',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCirIVzy3qbKV9_WVlE9zpEt3Wpknhel30',
    appId: '1:887229843621:android:b156ef1b5fe74a6b1ae54c',
    messagingSenderId: '887229843621',
    projectId: 'assignment2-2b662',
    storageBucket: 'assignment2-2b662.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrmEy4yQhIhgwrZR2jwxYPrPok19Jz6yM',
    appId: '1:887229843621:ios:6b7404447def030e1ae54c',
    messagingSenderId: '887229843621',
    projectId: 'assignment2-2b662',
    storageBucket: 'assignment2-2b662.firebasestorage.app',
    iosBundleId: 'com.example.assignment2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrmEy4yQhIhgwrZR2jwxYPrPok19Jz6yM',
    appId: '1:887229843621:ios:6b7404447def030e1ae54c',
    messagingSenderId: '887229843621',
    projectId: 'assignment2-2b662',
    storageBucket: 'assignment2-2b662.firebasestorage.app',
    iosBundleId: 'com.example.assignment2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCy-gHX38U33SshmMhcfGEoo_9dq0if7Jw',
    appId: '1:887229843621:web:f36bf889e1539c181ae54c',
    messagingSenderId: '887229843621',
    projectId: 'assignment2-2b662',
    authDomain: 'assignment2-2b662.firebaseapp.com',
    storageBucket: 'assignment2-2b662.firebasestorage.app',
    measurementId: 'G-5QFZNQTTYQ',
  );
}
